FROM maven:latest AS MAVEN_BUILD
COPY ./ /build
WORKDIR /build
RUN mvn clean package

FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=MAVEN_BUILD /build/target/backend-0.0.1-SNAPSHOT.jar /app/
ENTRYPOINT ["java", "-jar", "/app.jar"]
