FROM openjdk:17-jdk-slim
WORKDIR /app

# Copy the Maven dependencies from the cache
COPY ~/.m2 /root/.m2

# Copy the application JAR
COPY target/backend-0.0.1-SNAPSHOT.jar /app

ENTRYPOINT ["java", "-jar", "/app/backend-0.0.1-SNAPSHOT.jar"]
